name: Unit testing with pytest

on: [push] # when should we run this action

jobs: # what should we do when it is run
  build:
    runs-on: ubuntu-latest # platform it runs on
    steps:
    - uses: actions/checkout@v2 # checkout your code
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # specify python version
    - name: Install dependencies # which libraries do we need for testing
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install numpy
      run: pip install numpy
    - name: Test with pytest
      run: |
        pip install pytest
        pytest spring_constant_unittest.py
